langauge: go

go:
    - 1.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmagic-dev

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get gopkg.in/yaml.v2
  - go get github.com/mitchellh/go-homedir
  - go get github.com/syndtr/goleveldb/leveldb
  - go get -v -d ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: make test

notifications:
    email:
        on_success: change
        on_failure: always
