langauge: go
sudo: false
go:
    - 1.6
    - 1.7

before_install:
    - cp .netrc ~
    - go get github.com/tools/godep

install:
    # Install the testing specific dependencies
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - go get github.com/mattn/goveralls

    # Install the project specific dependencies
    - godep restore

script: make citest

notifications:
    email:
        recipients:
            - benjamin@bengfort.com
        on_success: change
        on_failure: always
