language: go

go:
    - 1.7
    - 1.8

before_install:
    - cp .netrc ~
    - go get github.com/tools/godep

install:
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - go get github.com/mattn/goveralls
    - godep restore

script: make citest

notifications:
    email:
        recipients:
            - bengfort@cs.umd.edu
            - keleher@cs.umd.edu
        on_success: change
        on_failure: always
