langauge: go
sudo: false
go:
    - 1.5

go_import_path: github.com/bbengfort/flow

install:
    # Add Godeps dependencies to GOPATH and PATH
    - export GOPATH="${TRAVIS_BUILD_DIR}:$GOPATH"
    - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
    - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
    - export PATH=$PATH:$HOME/gopath/bin

before_script:
    # Install the testing specific dependencies
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega

    # Collect the build dependencies from the flow project
    - got get -v -t ./...

script: make citest

notifications:
    email:
        recipients:
            - bengfort@cs.umd.edu
        on_success: change
        on_failure: always
