// Code generated by protoc-gen-go.
// source: blobs.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	blobs.proto
	service.proto

It has these top-level messages:
	PushRequest
	PushReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PushRequest initiates the first phase of Anti-Entropy by letting another
// node in the system know the current state of the blob tree.
type PushRequest struct {
	Count uint64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Size  uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PushRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// PushReply allows the remote node to respond with a list of blobs to request
// from the initiating server.
type PushReply struct {
	Sync bool `protobuf:"varint,1,opt,name=sync" json:"sync,omitempty"`
}

func (m *PushReply) Reset()                    { *m = PushReply{} }
func (m *PushReply) String() string            { return proto.CompactTextString(m) }
func (*PushReply) ProtoMessage()               {}
func (*PushReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PushReply) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "rpc.PushRequest")
	proto.RegisterType((*PushReply)(nil), "rpc.PushReply")
}

func init() { proto.RegisterFile("blobs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x32, 0xe7, 0xe2,
	0x0e, 0x28, 0x2d, 0xce, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x4d,
	0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0x70, 0x84, 0x84, 0xb8,
	0x58, 0x8a, 0x33, 0xab, 0x52, 0x25, 0x98, 0xc0, 0x82, 0x60, 0xb6, 0x92, 0x3c, 0x17, 0x27, 0x44,
	0x63, 0x41, 0x4e, 0x25, 0x58, 0x41, 0x65, 0x5e, 0x32, 0x58, 0x17, 0x47, 0x10, 0x98, 0x9d, 0xc4,
	0x06, 0xb6, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xad, 0xf4, 0x3d, 0x91, 0x74, 0x00, 0x00,
	0x00,
}
